### PR TITLE
removed FA from project; updagraded to latest normalize

### PR DESCRIPTION
**Pull request by josephgknox**
# READY FOR REVIEW

# Summary
- Removed FontAwesome from project entirely
- Upgraded to latest version of normalize

# Needed By (Date)
- N/A

# Urgency
- N/A

# Steps to Test

1. Pull this branch
2. Ensure FA is gone
3. Ensure new normalize is added (8.0.0)

# Affected Projects or Products
- Decanter
- Stanford Basic

# Associated Issues and/or People
- https://github.com/SU-SWS/decanter/issues/99
- https://github.com/SU-SWS/decanter/issues/102

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by josephgknox** [comment]
Cc: @pookmish

**Comment by sherakama** [comment]
This looks good to me.

@JBCSU & @AlishaOber  
This PR removes Font Awesome, and subsequently, 2300 lines of css from the rendered output as FA is not being utilized in any of the components at the moment. 

This also updates to the latest version of normalize.css.

Please have a review and let me know if there are any issues with these changes.

**Comment by pookmish** [comment]
@josephgknox looks like some conflicts in this now.

**Comment by josephgknox** [comment]
@pookmish yeah, thanks for keeping your eyes on this. We had merged in another branch off of master that still have the legacy stuff in there (since this one has not been merged). I've resolved the conflicts.

**Comment by sherakama** [comment]
Wonderful. Thank you.

**Pull request merged**
