### PR TITLE
ADAPT 1756 - Continuous v7 prep work

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
Screen Shot 2021-02-03 at 10 26 46 PM
👀  I did npm run publish - should I try something else instead? @sherakama

**Comment by sherakama** [comment]
I think we may have been using `npm run build` so that the css is readable and usable until we get documentation about all the classes.

**Comment by sherakama** [comment]
These look good. I am happy to keep them rolling in if you're ready.

**Comment by yvonnetangsu** [comment]
> These look good. I am happy to keep them rolling in if you're ready.

@sherakama I saw your comment late so I pushed some more stuff before the dev chat. I actually removed the whole "button" folder in components in one commit, since we have html `<button>` styles in the base css so those are taken care of if people want their buttons to look somewhat decent. What do you think?

**Review by sherakama — APPROVED** [review]
GTG

**Comment by sherakama** [comment]
If we bring the su-button back later we can. For those that want to use just the utility classes and not the base styles.

**Pull request merged**
