### PR TITLE
Multi menu

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- A multiple level alternative primary menu.
- Accordion and split toggle options. 

# Needed By (Date)
- ?

# Urgency
- ?

# Steps to Test

1. Review the code then...
2. Navigate to https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa/item-components-multi-menu.html
3. Review each variant for color, size, alignment, and overall aesthetics. 
4. Review the click behavior of each navigation and level both on mobile and desktop sizes
5. Review the keyboard navigation in both mobile and desktop
* Esc, Home, End, Space, Return, Left, Right, Up, Down
6. Run an accessibility scan
7. Review on Browsers

# Affected Projects or Products
- D8CORE
- Decanter

# Associated Issues and/or People
- @kerri-augenstein 
- D8CORE-71
- @cjwest if you would like to add in any notes of 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
Looks like I still have some IE11 JS work to do. Please ignore that for now.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
Ok, got most of the IE JS issues sorted. Should be GTG now.

**Comment by yvonnetangsu** [comment]
@sherakama @kerri-augenstein - 
1. I remember @kerri-augenstein mentioned at one point that the split button is mobile-only. The desktop navs (horizontal menu) should behave like the one on Princeton site where drop down displays on hover while parent link is a clickable link. I personally prefer this over the `.su-multi-menu--buttons` behavior (though it should have a caret or something to indicate parent items with a drop down menu):
https://www.princeton.edu/

2. If we decide to test out the split button for desktop nav, are we not going with the circular buttons (Navigation Toggle component)? I like the animation on the carets for the `.su-multi-menu--buttons` variants currently, but I'm not sure it's obvious that it's a separate clickable thing.

3. I'm still not crazy about the + sign on the top level (desktop) .su-multi-menu--accordion (inside the drop down is fine). It's kind of a rare pattern so I'm worried that it might be confusing. Will we do a user testing for desktop (horizontal) nav? I know SWS is doing a user testing for mobile nav and I'm totally fine with the +/- sign on all levels of mobile nav, but the desktop experience is so different I feel like it needs its own test.

**Comment by yvonnetangsu** [comment]
@kerri-augenstein @sherakama 
Is it possible we do a desktop user testing to compare these options?  My current preference is 3 > 1 > 2 > 4.

1. Our current Main Nav component (click to expand dropdown)
2. Same as above, but with the new "+" sign instead of caret.
3. The Princeton style (hover to reveal dropdown, parent link still clickable) - I think this is the same as our Main Nav no-js version.
4. The split button (parent link, with toggle caret) - maybe 2 versions, one with the circular toggle, one with the caret toggle.

I'm personally really curious what's the most user-friendly version myself and I'm open to change, but I don't feel like we can really determine which one is better without doing desktop user testing to compare these 🤔

**Comment by kerri-augenstein** [comment]
I think some things got lost in the fray. I have a 2hr research session over the decanter session today, so I will not be able to be present. I think we need to find time quickly to talk through this. I think what I'm seeing on the Tugboat preview is not quite what we want. But it's hard to say.

Ideally there would be two conventions to test.

**Spilt button** 
1. A user can click on the text, and go to the page, regardless if a dropdown arrow icon is present or not (Mobile + Desktop)
2. Desktop with dropdown arrow: on hover, the user see the dropdown appear 
3. Mobile with dropdown arrow: a user can click on the expand/collapse arrows to see nested menus

https://www.brown.edu/academics/undergraduate is the closest for this interaction

**"Overview" interaction**
1. A user can only click on the text, and go to the page if an arrow _is not_ present. 
2. Desktop + Mobile with dropdown arrow: a user must click the text and/or dropdown arrow to reveal dropdown menu. The only way to get to the page is to click on the "Overview" link presented as the first option in the dropdown menu.

https://cardinalatwork.stanford.edu/ is this interaction

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by yvonnetangsu** [comment]
> @sherakama @yvonnetangsu
> 
> I think some things got lost in the fray. I have a 2hr research session over the decanter session today, so I will not be able to be present. I think we need to find time quickly to talk through this.
> 
> I think what I'm seeing on the Tugboat preview is not quite what we want. I am looking at the Main Navigation section.
> 
> What I think I'm seeing here on tugboat, is that all instances are the "Overview" interaction. But maybe that's what you want us to see on this branch Shea?
> 
> Ideally there would be two conventions to test.
> 
> **Spilt button**
> 
> 1. A user can click on the text, and go to the page, regardless if a dropdown arrow icon is present or not (Mobile + Desktop)
> 2. Desktop with dropdown arrow: on hover, the user see the dropdown appear
> 3. Mobile with dropdown arrow: a user can click on the expand/collapse arrows to see nested menus
> 
> https://www.brown.edu/academics/undergraduate is the closest for this interaction
> https://www.princeton.edu/ is another good reference for desktop interaction
> 
> **"Overview" interaction**
> 
> 1. A user can only click on the text, and go to the page if an arrow _is not_ present.
> 2. Desktop + Mobile with dropdown arrow: a user must click the text and/or dropdown arrow to reveal dropdown menu. The only way to get to the page is to click on the "Overview" link presented as the first option in the dropdown menu.
> 
> https://cardinalatwork.stanford.edu/ is this interaction

Yes, the Brown one looks good! The Cardinal at work on is like what we currently have.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by yvonnetangsu** [comment]
Keyboard behavior is perfect for the --accordion variants! 💯

**Comment by yvonnetangsu** [comment]
I don't think I can check for keyboard interaction for the split button/hover version now since using the hover behavior probably change everything. The desktop first level menu on Brown's site is interesting. For mouse user, the dropdowns expand on hover, but for keyboard users, it displays the toggle buttons to expand the dropdown. Maybe something worth looking at. Otherwise the Princeton one is nice too. For other behaviors, I would recommend that we follow what we have for the --accordion variants or the Secondary Nav as closely as possible. 
https://www.brown.edu/

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by cjwest** [comment]
Amazing!
Screen Shot 2019-11-08 at 4 15 42 PM

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
@kerri-augenstein @yvonnetangsu 

The latest changes to the keyboard navigation and visual styles are up. Based on the fancy brown main nav keyboard behavior I left the ability to focus on the caret using keyboard navigation for the first level desktop menu.  

Please have another review.

Thanks,

**Comment by yvonnetangsu** [comment]
> @kerri-augenstein @yvonnetangsu
> 
> The latest changes to the keyboard navigation and visual styles are up. Based on the fancy brown main nav keyboard behavior I left the ability to focus on the caret using keyboard navigation for the first level desktop menu.
> 
> Please have another review.
> 
> Thanks,

That's really cool! Love it!

Here comes the nitpicky stuff because that's my job:

1. For the split button variant, if you use keyboard to navigate on desktop, when your focus is on one of the down caret buttons and if you hit the down arrow, I think you might need a js preventdefault or similar, to prevent the little bit of page scroll. We did that for the main nav also.
2. Thanks for taking away the focus and hover responses for the down caret button. Could we take away the click response also? Right now, if you click the down caret on the split button nav, the button kind of reveal itself. It might be less confusing if it remains the same (and probably change the cursor to normal and not the hand since for mouse user, the caret is simply a decorative icon).

More coming soon, but this is looking great!

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by yvonnetangsu** [comment]
Thanks for the change to the down arrow. I have one more down arrow suggestion - it's up for discussion.

In the split button nav, assuming keyboard user:
I like how when you're on desktop top level, when you hit the down arrow on the caret button, it opens up the submenu. Could we do the same for Secondary nav and also the caret button in the split button nav dropdowns too?

When you're on a link inside a dropdown (or Secondary Nav any level), the down arrow currently move you up and down the link list which is great and intuitive (no change needed), but when your focus is on the round caret button, I feel like hitting the down arrow should open up the submenu like when you're on the top level of the split button nav.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Comment by sherakama** [comment]
@kerri-augenstein @yvonnetangsu 

Please clarify if my understanding is wrong but the goal is to continue testing on these two models and then to boil it down to one option that will be the go-to option in Decanter correct?

Does that mean the same thing for secondary nav or will we continue to have two options there?

**Comment by kerri-augenstein** [comment]
@sherakama , @yvonnetangsu 
That is also my understanding. I am waiting for PCard approval to send another round of navigation testing through to Userbob. After that round, I too am hoping that we will be able to pick **one** of the two current models, and deprecate the alternative.

**Comment by sherakama** [comment]
Wonderful. 

Yes, the secondary navigation I was referring to is the sidebar nav. Ok, I will leave those alone as is.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr534-parmvermnambmpeveqrtf0liqpzssf2y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3

Visual Diffs:
- https://dashboard.tugboat.qa/5dbc91aa53999ad72936a6f3/visualdiffs

**Pull request closed without merging**
