### PR TITLE
Restore .centered-container and fix webpack alias for font-awesome.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW/

# Summary
- Restores missing layout helper class.
- Fixes webpack build 

# Needed By (Date)
- Whenever

# Urgency
- low/medium, webpack builds fail at the moment.

# Steps to Test

1. Check out this branch
2. Compile `npm run build`
3. Review markup

# Affected Projects or Products
- V6+

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr605-jabeq8mcvlf7aptoq8bpmerxqfarsqcj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e18efeffa8a5ed937ea5639

**Comment by sherakama** [comment]
At the moment there is nothing that allows us to build anything previewable just in this repo. That is an obvious pain point and why tugboat is pulling decanter-web for that work. We should think of a solution we would want to build in.

**Comment by kgcreative** [comment]
If you are building with Netlify, you can use build hooks to build deploy previews on either a PR or on a feature branch. https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

**Comment by sherakama** [comment]
Happy New Year @kgcreative 

We've got the build previews working on the `https://github.com/SU-SWS/decanter-web` repo but haven't looked into wiring up this repo. Interesting thought.

**Pull request merged**
