### PR TITLE
Create Aspect Ratio Mixin

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# NOT READY

# To Do:
- [x] Create Aspect Ratio Mixin Code
- [ ] Create Aspect Ratio Mixin Documentation 

# Summary
- PR resolves issue #310 

# Needed By (Date)
N/A

# Urgency
N/A

# Steps to Test

1. Pull this branch
2. Compile style guide
3. Review documentation in the example section (Section 6 Mixins) 

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- #310 
- Anyone who should be notified? @buttonwillowsix @yvonnetangsu 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by buttonwillowsix** [comment]
@rebeccahongsf I will take this over for now. :)

**Comment by yvonnetangsu** [comment]
@rebeccahongsf @sherakama Hey there - just want to check in and see what's the status of this PR 😄 We could use this mixin for the media field component (will be used in cards). Let me know if I could help with reviewing etc.

**Comment by sherakama** [comment]
@yvonnetangsu 

If you need this in your work feel free to merge it into your working branch.

**Comment by sherakama** [comment]
@yvonnetangsu @rebeccahongsf 

I took a stab at cleaning up the branch and merging it with the latest work from the master branch. I also moved a couple of things around and deleted the duplicate example template.

Please let me know if this makes sense as I wasn't 100% sure what the desired outcome was supposed to be.

**Comment by yvonnetangsu** [comment]
@rebeccahongsf @sherakama - I did some touch up and added 3 use cases in the example section (Core -> Helpers -> Aspect Ratio Container. Please let me know what you think.

**Pull request merged**
