### PR TITLE
Removed extra quote

### PR DESCRIPTION
**Pull request by pookmish**

### CODE REVIEW

**Review by yvonnetangsu — APPROVED** [review]
GTG - thanks @pookmish

**Comment by yvonnetangsu** [comment]
@sherakama Any idea why the preview generation failed - is it related to the recent v6 package updates?

**Comment by yvonnetangsu** [comment]
Merging this in as I don't think this is related to Decanter itself, but more likely due to the preview site build. This PR change is pretty safe.

**Comment by jenbreese** [comment]
Boy you are fast. Looks good to me too. Thanks for finding and fixing.

**Comment by pookmish** [comment]
Thanks :smile:

**Comment by sherakama** [comment]
> @sherakama Any idea why the preview generation failed - is it related to the recent v6 package updates?

Probably this: https://github.com/SU-SWS/decanter/commit/af5267f17d5b2f4d5e6a2f420f866f81df8ead7d

**Comment by sherakama** [comment]
and this: https://github.com/SU-SWS/decanter/commit/45d58ff37d5b2ab6830858d060be1987001aa844

**Pull request merged**
