### PR TITLE
Breakpoint helper improvements

### PR DESCRIPTION
**Pull request by kgcreative**
Addresses #34
- Add ‘helpers’ to base. Instantiate ‘breakpoint helper’ there. This is where things like ‘.center’ ‘.sr-only-text’, etc and other helper classes can exist if we decide we want them. Maybe helpers can have true/false configuration settings somewhere.

### CODE REVIEW

**Comment by sherakama** [comment]
I like this separation. 

My only question is does this helper belong in 'components' instead of base? I think this could live as it's own thing there.

**Comment by kgcreative** [comment]
I don't have a strong feeling of where it belongs. I figured a 'helpers' rollup in base could conditionally call the component, in addition to things like `.center` `.sr-only-text`, `.sr-only-element`, any visibility classes, maybe some grid classes if we ever wanted to go that route. I'm also ok with not calling that component anywhere and removing the true/false flag, and just let individual developers instance those as needed.

**Comment by sherakama** [comment]
In our very own comments

> Base rules consist of styling for HTML elements only, such as used in a CSS
> reset or Normalize.css. Base rules should never include class selectors.

We should play by there rules.

If you don't have a strong feeling about this I would like to move it to components.

**Comment by kgcreative** [comment]
- Refactored helpers.
- Introduced some placeholders

**Comment by kgcreative** [comment]
@sherakama - bump

**Comment by sherakama** [comment]
Ah sorry, thanks for the reminder. I'll look at this later today.

**Comment by sherakama** [comment]
@kgcreative,

I put the components in their own folder as this directory will likely explode next week with new components and we want to keep them separate. Helpers became a component as well. Not sure if that is the long term place for that kind of thing yet or not. Fixed up a few roll ups and compiled css.

**Comment by kgcreative** [comment]
Works for me! Thank you

**Pull request merged**
