### PR TITLE
D8 core 724 button hover

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW

# Summary

Hover and focus should rely on something other that a color change. I put in an underline to indicate the change
https://stanfordits.atlassian.net/browse/D8CORE-724

# Needed By (Date)
- When does this need to be merged by?
Soon.

# Urgency
- How critical is this PR?
Would like it for DecanterPalooza

# Steps to Test

Check out this branch
Verify the button hover, active, and focus work as expected

# Affected Projects or Products

# Associated Issues and/or People
- JIRA ticket: https://stanfordits.atlassian.net/browse/D8CORE-724

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr537-aqqiklwvqgdl0fkvzh7nikexd7tcgz7x.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd

Visual Diffs:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd/visualdiffs

**Comment by sherakama** [comment]
@kerri-augenstein re: https://stanfordits.atlassian.net/browse/D8CORE-724

**Comment by sherakama** [comment]
Thanks @cjwest,

If you're looking to get rid of the button jumping have a look at the examples on this page for how they did it: https://www.w3.org/TR/wai-aria-practices/examples/button/button.html

**Comment by sherakama** [comment]
Also, @cjwest you need to update your local master branch. It seems to a bit behind.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr537-aqqiklwvqgdl0fkvzh7nikexd7tcgz7x.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd

Visual Diffs:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd/visualdiffs

**Comment by yvonnetangsu** [comment]
Hey @cjwest , agree that we need something other than color change for button hover/focus state. What do you think about just adding an underline to the text instead? That would work better in the buttons in the CTA component for example.

**Comment by cjwest** [comment]
Hi @yvonnetangsu, 
I appreciate your thoughts on this! I think that this should have styling that works well with the rest of the site. I'm happy to switch to underlines. 

Let me know if you want to run with it and create a PR. Otherwise, I can propose something.

**Comment by sherakama** [comment]
@cjwest go ahead and run with it.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr537-aqqiklwvqgdl0fkvzh7nikexd7tcgz7x.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd

Visual Diffs:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr537-aqqiklwvqgdl0fkvzh7nikexd7tcgz7x.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd

Visual Diffs:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd/visualdiffs

**Comment by cjwest** [comment]
Hi @yvonnetangsu,

I switched from the outline to the underline. Take a look and if you like it, hit "Squash and merge".

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr537-aqqiklwvqgdl0fkvzh7nikexd7tcgz7x.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd

Visual Diffs:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd/visualdiffs

**Comment by yvonnetangsu** [comment]
@cjwest @sherakama Hm....I don't think this PR is for merging into master - looks more like a v6 merge to me 🤔

**Comment by cjwest** [comment]
Oh, thank you, @yvonnetangsu, for the clarification! I was debating that.

**Comment by yvonnetangsu** [comment]
> Oh, thank you, @yvonnetangsu, for the clarification! I was debating that.

Did you do a npm run build, @cjwest ? Looks like all the dist/ asset files were removed.

**Comment by sherakama** [comment]
Proper branch set and compiled.

Ready for review.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr537-aqqiklwvqgdl0fkvzh7nikexd7tcgz7x.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd

Visual Diffs:
- https://dashboard.tugboat.qa/5dcde38731108c02b04ad5dd/visualdiffs

**Pull request merged**
