### PR TITLE
Lando db gone

### PR DESCRIPTION
**Pull request by sherakama**
@JBCSU 

Thanks for that pull request. That does fix the MySQL issue on OSX, but we are not using mysql for this project. Perhaps we just get rid of it so that it doesn't cause any more issues.

Here is a PR to remove the DB and just run Apache/PHP

Thoughts?

### CODE REVIEW

**Comment by JBCSU** [comment]
This is so much better than my lame workaround. Thanks!

Apologies for not taking the time to learn lando enough to figure out how to build without a db.

**Comment by JBCSU** [comment]
Why do we need 3 appservers / url's?

**Comment by sherakama** [comment]
Hey @JBCSU,

There is nothing lame about adding the MSYQL fix. It was a fix. We're talking code and there are many different solutions to our problems. This is just another one and a good time to talk about it and both of us learn. 

I figured getting rid of something we weren't using might be better long term. The trade off was that I had to add the proxy lines in which it gave us three urls. For some reason when I removed the LAMP recipe I was not getting my `decanter.sws` proxy to show up and only localhost was showing. I like my clean urls without port numbers so I put two of the conventions that we use for local development urls. 

I'd rather it have the original behaviour where it picks up my proxy settings from `~/.lando/` but I wasn't able to quickly figure out how to do that. Perhaps one of us can find the time to find out before this gets merged.

**Comment by sherakama** [comment]
As to the composer error, it looks like it was a network issue. The setup processes were unable to load the remote data point and failed to complete. I have seen this often on the Stanford network and it is annoying but usually resolvable by simply trying again.

**Pull request merged**
