### PR TITLE
559 Mixin SASSDoc Comments

### PR DESCRIPTION
**Pull request by buttonwillowsix**
# NOT READY

# Summary
- Adding comments to mixins

# Needed By (Date)
- End of Sprint

# Urgency
- 

# Steps to Test

Assuming your local decanter is linked to your local decanter-web

1. Pull this branch to local.
2. Switch to your local decanter-web,
3. Run npm run sassdoc
4. Run npm start
5. Go to http://localhost:3000/docs/scss/index.html

# Affected Projects or Products
- SASS Docs
- Decanter Website

# Associated Issues and/or People
- @rebeccahongsf 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by buttonwillowsix** [comment]
SASSDocs doesn't really allow for group descriptions. We don't have a ton of these in mixins so far, but the modular spacing one seems handy and I am going to try to figure out the best approach.

**Comment by buttonwillowsix** [comment]
Are the descriptions for big-paragraph and small-paragraph correct? Seeems like alt text

**Comment by buttonwillowsix** [comment]
I am getting a sassdocs error, but having a hard time figuring out where it is coming from and if it is related to something in my comments:
[ERROR] Template render error: (/Users/denadebry/.nvm/versions/node/v11.14.0/lib/node_modules/sassdoc/node_modules/sassdoc-theme-default/views/documentation/index.html.njk)

**Comment by rebeccahongsf** [comment]
I received the same error as well when I pulled this branch down to my local 😞 
` [ERROR] Template render error: (/Users/rebeccahong/programming/decanter-web/node_modules/sassdoc-theme-default/views/documentation/index.html.njk)
`

**Pull request merged**
