### PR TITLE
V7 colors

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- Update v7 color variables. Add Digital Green, replace Fog with Foggy (old Fog color is now su-color-foggy-light). Bright Blue is now Digital Blue.

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Look at code

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
@yvonnetangsu How does this relate to https://github.com/SU-SWS/decanter/pull/694?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu How does this relate to #694?

#694 looks stale to me - those colors name mentioned have since been changed. However, the colors themselves are in v7 but with different new names (@kerri-augenstein suggested some of these changes)

**Comment by sherakama** [comment]
Can we close #694 then in favor of this one?

**Comment by yvonnetangsu** [comment]
> Can we close #694 then in favor of this one?

Yes, I believe so. I'll ping @katrialesser tomorrow and let her know since she was working on #694. The new colors are in branch v7 and in the v6 PR so she'll be able to pull from either if the colors are needed.

**Review by sherakama — APPROVED** [review]
GTG

**Comment by yvonnetangsu** [comment]
@sherakama Think we could cut a new release maybe after merging Rebecca's branch?

**Comment by sherakama** [comment]
Sure. Can do.

**Pull request merged**
