### PR TITLE
Update _lockup.scss

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
Hmmm odd....seems like they're still not showing up 🤔 
https://deploy-preview-846--decanter-v6.netlify.app/component/identity-lockup/

**Comment by yvonnetangsu** [comment]
I sort of remember that the formatting of the twig comments was really finicky. Maybe even moving that comment to the top breaks it because it creates a 2nd paragraph.

**Comment by sherakama** [comment]
This (https://github.com/SU-SWS/decanter-web/pull/89/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R43)
Will need to change to this branch in order to pull the new build

**Review by yvonnetangsu — APPROVED** [review]
GTG - thanks, Shea!

**Comment by yvonnetangsu** [comment]
@sherakama Does this need a beta tag before merging?

**Comment by sherakama** [comment]
We don't have an auto release in v6. I suppose I could pull that back.

**Pull request merged**
