### PR TITLE
D8CORE-925: changing the icon to red from the grey

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW
- Should be ok'ed by @kerri-augenstein as well. She ok'ed it in the screenshots from the ticket.

# Summary
- Updated the search icon color to red. 

# Needed By (Date)
- Feb 12

# Urgency
- Low. Accessibility issue.

# Steps to Test

1. Pull this branch.
2. Build.
3. View the top right search icon and verify it is red and not grey.
4. Make sure when using keyboard navigation that the focus is correct when on the search magnifying glass.

# Affected Projects or Products
- Our base theme will use it. 

# Associated Issues and/or People
- D8CORE-925
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- @kerri-augenstein 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr616-p7adaqunncmadf27jshuwmisv50ozk32.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e3db70d9366b16c6519692a

Visual Diffs:
- https://dashboard.tugboat.qa/5e3db70d9366b16c6519692a/visualdiffs

**Comment by jenbreese** [comment]
When I look at the [tugboat environment](https://pr616-p7adaqunncmadf27jshuwmisv50ozk32.tugboat.qa/component/identity-masthead), I don't see the icon changed to red. It should work right?

**Comment by sherakama** [comment]
Yeah, one would expect that to show up. Not sure why it is not at the moment but the code looks solid.

**Comment by yvonnetangsu** [comment]
Hmm...How come these recent tugboat previews don't seem to include images?
On the homepage and on this page for example
https://pr616-p7adaqunncmadf27jshuwmisv50ozk32.tugboat.qa/page/about-projects-that-use-decanter/
🤔 
I'm not seeing the icon color change either. When I open that image URL directly in the browser, it's still showing me the grey one, but the code looks good - is it a LFS thing?

**Comment by sherakama** [comment]
Yeah, tug hasn't been wired up with LFS yet. It's on my backlog.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr616-p7adaqunncmadf27jshuwmisv50ozk32.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e3db70d9366b16c6519692a

Visual Diffs:
- https://dashboard.tugboat.qa/5e3db70d9366b16c6519692a/visualdiffs

**Comment by sherakama** [comment]
Shows up as red for me in my integration test. 
GTG.

**Pull request merged**
