### PR TITLE
D8CORE-2950: adding mailto icon

### PR DESCRIPTION
**Pull request by cjwest**
#  READY FOR Review

Thank you to Rebecca for creating these icons!

# Summary
This PR is for adding needed icons.
We need an email icon as a .png. Until that icon is available, I'm piloting the work and getting the document icon into decanter.
This also includes the document icons.

# Needed By (Date)

# Urgency

# Steps to Test
 See directions in https://github.com/SU-SWS/stanford_profile_helper/pull/53

# Affected Projects or Products
-  D8Core

# Associated Issues and/or People
- JIRA ticket
https://stanfordits.atlassian.net/browse/D8CORE-2950
- Other PRs 
https://github.com/SU-SWS/stanford_profile_helper/pull/53
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
See issue:
SU-SWS/decanter#621

We have the icons displayed on this page:
https://amptesting.sites.stanford.edu/interior-page/wysiwyg/icons-links
In this ticket: https://stanfordits.atlassian.net/browse/D8CORE-2950
we're adding icons to display in the WYSIWYG. SVGs don't work in the WYSIWYG so I'm using PNGs.

- Anyone who should be notified? (`@mention` them here)

I'm not sure if I made these icons correctly. I'd appreciate Kerri's oversight

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by kerri-augenstein** [comment]
@cjwest is there a spot where I can see a screenshot or a link to visit? I did review the jira ticket. 

Couple questions:

- Was there discussion about where the icon should display (left or right of the text)? 
- Will the icon display if a mailto link is present inside of body copy?

**Comment by cjwest** [comment]
Hi @kerri-augenstein,

No, there was no intentional discussion about where the email icon will display
We have the icons as SVGs displayed as body copy on this page:
https://amptesting.sites.stanford.edu/interior-page/wysiwyg/icons-links
SVGs don't work in the WYSIWYG so I'm using PNGs.

**Comment by kerri-augenstein** [comment]
@cjwest 

Ahhh the link you shared is PERFECT. Okay, exactly as I suspected. I think in the case of email, we want the icon to be leading rather than trailing like all of our other cta's with icons. 

How possible is that given the current system of links with icons? 

Additionally, for the first example — the big button — possible to increase the icon size? 

I think we can go: 
```
a.mailto svg {
height: 23px; 
width: 27px; 
}
```
Current:
current

Updated:
bigger-icon

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr776-17gw9ibl8deffabuconcfnyfu0nrzuhs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5fd3a26bd923e54a2a4bb0ad

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr776-17gw9ibl8deffabuconcfnyfu0nrzuhs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5fd3a26bd923e54a2a4bb0ad

**Comment by cjwest** [comment]
@yvonnetangsu ,
The PNGs look like they'll work, and I'd like a second set of eyes.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr776-keqzm51lryygwn8ngfpaz4k0lbon2od6.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/600f0d30a3c9970f9fbd98ef

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu ,
> The PNGs look like they'll work, and I'd like a second set of eyes.

@cjwest Looks like this PR is for adding the needed PNG files, but some SVG files are added as well? I don't see any reason why the PNG wouldn't work. Only suggestion I have might be to use the brand new color names (in Decanter release 6.2.2). For example, bright-red is renamed to digital-red, and bright-blue is renamed to digital-blue 😃

**Comment by yvonnetangsu** [comment]
And as Kerri said, it seems like the big button would need the larger version of the icon.

**Comment by cjwest** [comment]
Hi @yvonnetangsu,
Thanks for your feedback!

1. I will update the names on the .pngs.
2. On HAI, we needed .svgs because of the way we were using them in CSS. I'll take them out.
3. Re: > And as Kerri said, it seems like the big button would need the larger version of the icon.
Rebecca created both 24px and 30px sizes for each. Will that suffice?

**Comment by yvonnetangsu** [comment]
> Hi @yvonnetangsu,
> Thanks for your feedback!
> 
> 1. I will update the names on the .pngs.
> 2. On HAI, we needed .svgs because of the way we were using them in CSS. I'll take them out.
> 3. Re: > And as Kerri said, it seems like the big button would need the larger version of the icon.
>    Rebecca created both 24px and 30px sizes for each. Will that suffice?

Yes, perfect. Thank you @cjwest :)

**Comment by cjwest** [comment]
@yvonnetangsu,
I made changes per your suggestions. Let me know if there's anything else!

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr776-keqzm51lryygwn8ngfpaz4k0lbon2od6.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/600f0d30a3c9970f9fbd98ef

**Review by yvonnetangsu — APPROVED** [review]
Thanks for the rename, looks good to me @cjwest !

**Pull request merged**
