### PR TITLE
Tweaking modular-spacing mixin to be more user friendly

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- Tweaking the modular-spacing mixin so each individual property doesn't get wrapped into a separate set of media queries.
- It now follows the shorthand notation of padding/margin, e.g., `@include modular-spacing('margin', 3 null 2 -1);` will generate output for each breakpoint:
```
{
margin-top: calculate-modular-spacing(3); 
margin-bottom: calculate-modular-spacing(2);
margin-left: calculate-modular-spacing(-1);
}
```

# Needed By (Date)
- Whenever

# Urgency
- Not urgent

# Steps to Test

1. Pull this branch
1. Test on a component using e.g., `@include modular-spacing('margin', 0 -4 3 null);`
2. Run `grunt styleguide` and see if it produces the expected result.

# Affected Projects or Products
- Decanter
- event calendar

# Associated Issues and/or People
- @scott's event calendar

### CODE REVIEW

**Comment by sherakama** [comment]
This looks like a handy optimization. I like it. Couple of code climate fixes and this is gtg.

**Comment by josephgknox** [comment]
CC issues have been addressed.

**Comment by yvonnetangsu** [comment]
> CC issues have been addressed.
Thank you for the cc fix, @josephgknox! 👍 I start my day on the late side 😂

**Comment by josephgknox** [comment]
> > CC issues have been addressed.
> > Thank you for the cc fix, @josephgknox! 👍 I start my day on the late side 😂

Haha! Those who are productive as you need extra rest (gives us others a chance to catch up). :)

**Comment by yvonnetangsu** [comment]
@josephgknox , I'm just trying to catch up with you and @sherakama! I don't want to be freeloading  😹

**Pull request merged**
