### PR TITLE
199 add typography levels

### PR DESCRIPTION
**Pull request by JBCSU**
# NOT READY FOR REVIEW

# Summary
- TL;DR - Implement code structure to allow for skins and overriding values in skins

# Needed By (Date)
- Soon-ish

# Urgency
- Medium

# Steps to Test

1. TBD

# Affected Projects or Products
- Every blessed thing

# Associated Issues and/or People
- #217 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by buttonwillowsix** [comment]
Semantic names for all levels of typography and have them be responsive.
Class and mixin for all
Serif, Sans, Slab, etc.
5 font families x 16 semantic names for each, and 3 variants responsively for each.

**Comment by buttonwillowsix** [comment]
From original ticket https://github.com/SU-SWS/decanter/issues/199

Make this: https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Stanford-Design-Library?node-id=1%3A16

**Comment by sherakama** [comment]
@JBCSU is this PR still active or has it gone stale?

**Comment by JBCSU** [comment]
> @JBCSU is this PR still active or has it gone stale?

@sherakama I don't think it makes sense to continue work in this branch, but I had hoped that the work I've done in this branch might serve as a good foundation for a new branch / PR.

**Comment by sherakama** [comment]
Ok, we can keep the branch a little longer but I will close the PR. Thank you.

**Pull request closed without merging**
