### PR TITLE
Add first and last variants

### PR DESCRIPTION
**Pull request by sherakama**
# READY

# Summary
- Adds first/last variants out of the box

Re: https://github.com/SU-SWS/saa_alumni/pull/329

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
Oh TW actually supports first/last variants out of the box, but when using with the custom `children` variant, I found that the order matters, e.g., I recently found that `first:children:` works, but `children:first` didn't (at least for my specific case in My Account). So that might be what we need to do 😄

**Comment by sherakama** [comment]
> Oh TW actually supports first/last variants out of the box, but when using with the custom `children` variant, I found that the order matters, e.g., I recently found that `first:children:` works, but `children:first` didn't (at least for my specific case in My Account). So that might be what we need to do 😄

Huh, interesting.

**Comment by yvonnetangsu** [comment]
> > Oh TW actually supports first/last variants out of the box, but when using with the custom `children` variant, I found that the order matters, e.g., I recently found that `first:children:` works, but `children:first` didn't (at least for my specific case in My Account). So that might be what we need to do 😄
> 
> Huh, interesting.

I think they're going to iron that kink out probably sooner or later. I'm hopeful 🤞🏼

**Comment by sherakama** [comment]
Found this:
https://tailwindcss.com/docs/hover-focus-and-other-states#ordering-stacked-modifiers

Looks like order will matter for children

**Comment by yvonnetangsu** [comment]
> Found this: https://tailwindcss.com/docs/hover-focus-and-other-states#ordering-stacked-modifiers
> 
> Looks like order will matter for children

Interesting....that makes sense!

**Comment by sherakama** [comment]
Looks like a newer plugin for v3 also requires that the psuedo classes go before the children selectors: https://github.com/SamGoody/tailwind-children#psuedo-classes-psuedo-elements-and-state--eg-hover-after-open

**Comment by yvonnetangsu** [comment]
> Looks like a newer plugin for v3 also requires that the psuedo classes go before the children selectors: https://github.com/SamGoody/tailwind-children#psuedo-classes-psuedo-elements-and-state--eg-hover-after-open

This might be more promising!

**Pull request closed without merging**
