### PR TITLE
ADAPT-000: Link color utility

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- For Discussion
- This is to tackle changing backgrounds, text-color, and link color on the wrapper container.

# Needed By (Date)
- Whenever
- 
# Urgency
- None

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by yvonnetangsu — APPROVED** [review]
Interesting.... I think this would be useful as long as we use it carefully since it would override a utility class directly place on a link that's within that parent with the su-link-xx class. Nice tool for those WYSIWYG for sure though. GTG - we can always tweak later if we need to.
Screen Shot 2021-02-11 at 9 42 25 AM

**Comment by sherakama** [comment]
Yeah, I am not super fond of this approach but lacking the ability to get access to the individual links in something like a wysiwyg this might be a good enough get out of jail free card.

**Comment by sherakama** [comment]
After a little more research this morning I am not finding anything to influence me in a different direction at this point. Merge and use with caution for now.

**Comment by yvonnetangsu** [comment]
Sounds good to me - thanks for adding this!

**Pull request merged**
