### PR TITLE
Scale down type-a and type-b font size at xs and sm breakpoints, repurpose splash font and minor typography tweaks

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- Introduce a multiplier `$su-displays-mobile-factor` of 0.85 to scale down `@type-a` (h1) and `@type-b `(h2) and font-splash font sizes at `xs` and `sm` breakpoints.
- Repurpose `@font-splash`/`.su-font-splash` into a display type style that's more splashy - larger than h1 (modular-scale(5)).
- Finetune letter spacing of display types (approved by Kerri Augenstein).
- Add 6 Decanter class names `.su-type-a`, `.su-type-b` etc so developers can use them with the decanter.css file. Also add them to the styleguide.
- Other minor typography tweaks.

# Needed By (Date)
- N/A

# Urgency
- Not urgent

# Steps to Test

1. Pull this branch and build styleguide
2. Look at section Elements/Typography and check that the 6 new display styles (`.su-type-a` etc) are on the styleguide.
3. Check that for Display Type A and Type B, the font size scale down as discussed at `xs` and `sm` breakpoints.
4. Check that the new splash font style looks ok.
5. Check that the new letter-spacing finetuning looks ok and consistent with our other type styles.

# Affected Projects or Products
- Redwood WordPress
- Decanter

# Associated Issues and/or People
- #471 
- #501 
- @kerri-augenstein

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@kerri-augenstein , I remember you mentioned that you'd like to change the splash font into something different (larger than current type-A/h1)? If you could please let me know the font sizes, I can probably add that to this PR since it's related.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu let's go up to 56px or Modular Scale 5 for the Splash font. How does that sound?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu let's go up to 56px or Modular Scale 5 for the Splash font. How does that sound?

Sounds good to me - is that large enough for the hero area, e.g., for something like the SoE site?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu let's go up to 56px or Modular Scale 5 for the Splash font. How does that sound?

@kerri-augenstein I'm testing it out and it does look proportional (modular-scale 5). I'll show you tomorrow :)

**Pull request merged**
