### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Updates tugboat configuration

# Needed By (Date)
- Whenever

# Urgency
- Low

# Steps to Test

1. Validate that the build preview worked

# Affected Projects or Products
- Not much

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr520-sg8dem4rsllhoipte8jhfqkos0ne7nby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5db0a66844c5fa4c680f69c2

Visual Diffs:
- https://dashboard.tugboat.qa/5db0a66844c5fa4c680f69c2/visualdiffs

**Comment by yvonnetangsu** [comment]
Only issue is the visual diff still - got this message "There was a problem generating Visual Diffs for this preview."

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr520-sg8dem4rsllhoipte8jhfqkos0ne7nby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5db0a66844c5fa4c680f69c2

Visual Diffs:
- https://dashboard.tugboat.qa/5db0a66844c5fa4c680f69c2/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr520-sg8dem4rsllhoipte8jhfqkos0ne7nby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5db0a66844c5fa4c680f69c2

Visual Diffs:
- https://dashboard.tugboat.qa/5db0a66844c5fa4c680f69c2/visualdiffs

**Pull request closed without merging**
