### PR TITLE
DECANTER-193: Start of accordion and development environment.

### PR DESCRIPTION
**Pull request by sherakama**
# NOT READY

# Summary
- New Accordion Component
- A development environment to replace the KSS generator

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
@yvonnetangsu FYI. Not much progress on the accordion but I did manage to scaffold a small development environment to help with building out and testing stuff.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr642-2ecoydtenrl6wil4ge1ke1ogidckb2ha.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e

Visual Diffs:
- https://dashboard.tugboat.qa/5e6881b413ecdf48b84a366e/visualdiffs

**Comment by yvonnetangsu** [comment]
I know this still need some work but wondering if it's ok to merge as is? It would be nice to get that new development environment @sherakama set up into master 😄

**Comment by sherakama** [comment]
Let's mark it as experimental and merge it in.

**Comment by yvonnetangsu** [comment]
> Let's mark it as experimental and merge it in.

Cool. Thanks!!

**Pull request merged**
