### PR TITLE
Tweaking masthead lockup font size and spacing for XS to MD breakpoints

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# NOT READY

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr640-aeqes6vfrnwe1ux0g7ls8wbxq1jkyeux.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412

Visual Diffs:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr640-aeqes6vfrnwe1ux0g7ls8wbxq1jkyeux.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412

Visual Diffs:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr640-aeqes6vfrnwe1ux0g7ls8wbxq1jkyeux.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412

Visual Diffs:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr640-aeqes6vfrnwe1ux0g7ls8wbxq1jkyeux.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412

Visual Diffs:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr640-aeqes6vfrnwe1ux0g7ls8wbxq1jkyeux.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412

Visual Diffs:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr640-aeqes6vfrnwe1ux0g7ls8wbxq1jkyeux.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412

Visual Diffs:
- https://dashboard.tugboat.qa/5e603acd8bd53e4f29dd1412/visualdiffs

**Comment by yvonnetangsu** [comment]
I'm closing this one since it seems like it's not a priority anymore. Will revive if we need it again later.

**Pull request closed without merging**
