### PR TITLE
D8CORE-7111 | @jdwjdwjdw | Add Mastodon and google scholar icons and colors

### PR DESCRIPTION
**Pull request by jdwjdwjdw**
# NOT READY FOR REVIEW

# Summary
- [D8CORE-7111](https://stanfordits.atlassian.net/browse/D8CORE-7111): DEV | Social Media support

# Needed By (Date)
- When convenient

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

[D8CORE-7111]: https://stanfordits.atlassian.net/browse/D8CORE-7111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@jdwjdwjdw I believe the fontawesome version we currently have doesn't have the 2 new icons - Google Scholar and Mastodon only available in FA v6.

**Comment by jdwjdwjdw** [comment]
> @jdwjdwjdw I believe the fontawesome version we currently have doesn't have the 2 new icons - Google Scholar and Mastodon only available in FA v6.

Ah, thanks for the head's up! I'm seeing Mastodon [in v5](https://fontawesome.com/v5/icons/mastodon?f=brands&s=solid), but Google Scholar only [in v6](https://fontawesome.com/icons/google-scholar?f=brands&s=solid).

If I still wanted to use the Google Scholar FA logo, would the correct alternate step be to just download that svg and add it to our `src/img` folder?

**Comment by yvonnetangsu** [comment]
> > @jdwjdwjdw I believe the fontawesome version we currently have doesn't have the 2 new icons - Google Scholar and Mastodon only available in FA v6.
> 
> Ah, thanks for the head's up @yvonnetangsu ! I'm seeing Mastodon [in v5](https://fontawesome.com/v5/icons/mastodon?f=brands&s=solid), but Google Scholar only [in v6](https://fontawesome.com/icons/google-scholar?f=brands&s=solid).
> 
> If I still wanted to use the Google Scholar FA logo, would the correct alternate step be to just download that svg and add it to our `src/img` folder?

@jdwjdwjdw It's possible, but might need some update to the twig file and/or CSS depending on how the social media section is constructed :)

**Comment by jdwjdwjdw** [comment]
Closing this PR - I ended up [adding this support](https://github.com/SU-SWS/stanford_profile/pull/756) into our Stanford Basic theme instead of within decanter.

**Pull request closed without merging**
