### PR TITLE
Small Tweaks and Fixes

### PR DESCRIPTION
**Pull request by josephgknox**
# READY FOR REVIEW

# Summary
- Very small changes, but are being added so that they don't need to be overrode in project partials every time
- removed margin-top from heading 1's
- removed the hard-coded font family on buttons

# Needed By (Date)
- As soon as possible (would unblock some project work)

# Urgency
- N/A

# Steps to Test

1. Pull this branch
2. Ensure that tweaks are applied

# Affected Projects or Products
- decanter
- stanford_basic
- suhumsci (theme)

# Associated Issues and/or People
- N/A

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by josephgknox** [comment]
Cc: @bixgomez

**Comment by sherakama** [comment]
@josephgknox Can you clean up the codeclimate comments before merging.

**Comment by josephgknox** [comment]
@sherakama I'm feeling like we want to ignore these 4 CC issues, in this case. We would need to add a few extra (and arguably unnecessary) lines to the SCSS and nest deeper to address them. Thoughts?

**Comment by sherakama** [comment]
@josephgknox all good. But do you really need `a.selector`? could you get away without the tag on the selector or does some orther css scope blow out the styles?

**Comment by josephgknox** [comment]
@sherakama based on our conversation this morning (on Decanter vs Drupal/WP vs theme), I have made the related update (see last commit). This also addressed the CC issues.

**Pull request merged**
