### PR TITLE
Secondary nav js

### PR DESCRIPTION
**Pull request by sherakama**
# NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr529-ws7xcjlnrmfspon2ucxlwzmiwdakosw0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb

Visual Diffs:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr529-ws7xcjlnrmfspon2ucxlwzmiwdakosw0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb

Visual Diffs:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb/visualdiffs

**Comment by yvonnetangsu** [comment]
@sherakama , is this ready for review?

**Comment by sherakama** [comment]
No, not yet. Lots to do still.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr529-ws7xcjlnrmfspon2ucxlwzmiwdakosw0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb

Visual Diffs:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr529-ws7xcjlnrmfspon2ucxlwzmiwdakosw0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb

Visual Diffs:
- https://dashboard.tugboat.qa/5db864d353999a45362463eb/visualdiffs

**Pull request merged**
