### PR TITLE
Update _button.scss

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Make font weight stronger for buttons.

# Needed By (Date)
- ?

# Urgency
- ?

# Steps to Test

1. Review code
2. Review Tugboat environment for buttons

# Affected Projects or Products
- https://stanfordits.atlassian.net/browse/D8CORE-717

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/D8CORE-717
- @kerri-augenstein

### CODE REVIEW

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by sherakama** [comment]
@kerri-augenstein 
FYI

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by sherakama** [comment]
@cjwest

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by cjwest** [comment]
@sherakama or @yvonnetangsu,
Please review and let me know if there is anything else. If all is good, please merge.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by yvonnetangsu** [comment]
> @sherakama or @yvonnetangsu,
> Please review and let me know if there is anything else. If all is good, please merge.

@cjwest , Could we add a `font-weight: $su-font-regular;` to `.su-main-nav__toggle`? (main nav component)? Thanks!

**Comment by cjwest** [comment]
@yvonnetangsu,

If I change the font-weight here's how it looks in high contrast:

Screen Shot 2019-11-22 at 3 53 46 PM


Let me know if you're okay with that.

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu,
> 
> If I change the font-weight here's how it looks in high contrast:
> 
> Screen Shot 2019-11-22 at 3 53 46 PM
> 
> Let me know if you're okay with that.

@cjwest Yeah, I think that's ok. I like it at 400 font weight better since 600 makes it quite visually heavy compared to the lockup on mobile. Only a very small population would use the high contrast mode, and the hamburger icon is pretty well understood even without the word "menu".

Oops...I think I edited your comment instead of replying at first - I blame it on jetlag 😂

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by cjwest** [comment]
@yvonnetangsu,
Sounds good! Thanks for the confirmation.
Please review and if you like it, merge!

Happy Thanksgiving!

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by sherakama** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr536-5jghshzcy9w3pzkvvbku2t78gubmglgf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855

Visual Diffs:
- https://dashboard.tugboat.qa/5dcdc99b6871071f14745855/visualdiffs

**Comment by sherakama** [comment]
Compiled and pushed.

**Comment by cjwest** [comment]
@sherakama or @yvonnetangsu,

We have a policy that a person cannot merge his/her own work. Can I get one of you to merge this?

**Comment by yvonnetangsu** [comment]
> @sherakama or @yvonnetangsu,
> 
> We have a policy that a person cannot merge his/her own work. Can I get one of you to merge this?

Done! 🎉

**Pull request merged**
