### PR TITLE
ADAPT-2695: Add additional borderWidths

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- Add additional borderWidths

# Needed By (Date)
- tbd

# Urgency
- low

# Steps to Test

1. Pull this PR
2. Test borderWidth style (i.e. `su-border-7`)

# Affected Projects or Products
- https://github.com/SU-SWS/decanter-react/pull/50

# Associated Issues and/or People
- [ADAPT-2695](https://stanfordits.atlassian.net/browse/ADAPT-2695)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@rebeccahongsf Oh yay! Thank you 🥳  @sherakama Do we need to add any tags to get this to punch a release?

**Review by yvonnetangsu — APPROVED** [review]
GTG - just waiting to see if we need to add tags so we can get a release working 😄

**Comment by sherakama** [comment]
Yep. Need the alpha tag to trigger the release stuff.

**Review by sherakama — APPROVED** [review]
GTG

**Pull request merged**
